import type { Metadata } from "next";
import "./globals.css";
import SideNavigation from "@/components/Navigation/SideNavigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <div className=" container flex flex-row">
          <SideNavigation />
          {children}
        </div>
      </body>
    </html>
  );
}
